apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ .Release.Name }}-service
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.deployment.config.server.port }}
          env:
            - name: BAL_CONFIG_FILES
              value: "/home/ballerina/conf/Config.toml"
          volumeMounts:
            - name: websubhub-conf
              mountPath: /home/ballerina/conf
              readOnly: true
      volumes:
        - name: websubhub-conf
          configMap:
            name: websubhub-svc-cm
