deployment:
  replicas: 1
  image:
    repository: "wso2/wso2websubhub-consolidator"
    pullPolicy: IfNotPresent
    tag: "1.0.0-M1-RC4"

  config:
    server:
      port: 10001

    state:
      snapshot:
        topic: "websub-events-snapshot"
        consumerId: "websub-events-snapshot-consumer"
      events:
        topic: "websub-events"
        consumerId: "consolidator-websub-events-consumer"

    store:
      solace:
        url: "tcp://solace-pubsubplus-dev:55555"
        vpnName: "default"
        username: "admin"
        password: "password"
        consumerReceiveTimeOut: "10.0"
        admin:
          url: "http://solace-pubsubplus-dev:8080/SEMP/v2/config"
          username: "admin"
          password: "password"
          timeOut: "30.0"

logging:
  level: "INFO"

service:
  type: ClusterIP
  port: 10001

ingress:
  enabled: false
  hostname: wso2-websubhub-consolidator.local
  path: /consolidator
  pathType: Prefix
