[websubhub.config.server]
port = 9000
id = "websubhub-1"

[websubhub.config.server.secureSocket]
key.path = "conf/resources/wso2websubhub.jks"
key.password = "password"

[websubhub.config.state.snapshot]
url = "http://consolidator:10001/consolidator/state-snapshot"

[websubhub.config.state.events]
topic = "websub-events"
consumerIdPrefix = "websub-events-consumer"

[websubhub.config.store.jms]
initialContextFactory = "com.sun.jndi.fscontext.RefFSContextFactory"
providerUrl = "file:/home/wso2/jndi-bindings"
connectionFactoryName = "TestConnFac3"
username = "admin"
password = "password"

[websubhub.config.store.jms.consumer]
receiveTimeout = 10.0

[websubhub.config.delivery]
timeout = 60.0

[websubhub.config.delivery.retry]
count = 3
interval = 3.0
backOffFactor = 2.0
maxWaitInterval = 20.0
statusCodes = [500, 502, 503]

[ballerina.log]
level = "DEBUG"
