[websubhub.config.server]
port = {{ .Values.deployment.config.server.port }}
id = "{{ .Values.deployment.config.server.id }}"

[websubhub.config.server.secureSocket]
key.path = "{{ .Values.deployment.config.server.secureSocket.keystore.path }}"
key.password = "{{ .Values.deployment.config.server.secureSocket.keystore.password }}"

[websubhub.config.state.snapshot]
url = "{{ .Values.deployment.config.state.snapshot.url }}"

[websubhub.config.state.events]
topic = "{{ .Values.deployment.config.state.events.topic }}"
consumerId = "{{ .Values.deployment.config.state.events.consumerId }}"

[websubhub.config.store.solace]
url = "{{ .Values.deployment.config.store.solace.url }}"
messageVpn = "{{ .Values.deployment.config.store.solace.vpnName }}"
auth.username = "{{ .Values.deployment.config.store.solace.username }}"
auth.password = "{{ .Values.deployment.config.store.solace.password }}"

[websubhub.config.store.solace.consumer]
# receiveTimeout = {{ .Values.deployment.config.store.solace.consumerReceiveTimeOut }}
receiveTimeout = 10.0

[websubhub.config.store.solace.admin]
url = "{{ .Values.deployment.config.store.solace.admin.url }}"
# timeout = {{ .Values.deployment.config.store.solace.admin.timeOut }}
timeout = 30.0
auth.username = "{{ .Values.deployment.config.store.solace.admin.username }}"
auth.password = "{{ .Values.deployment.config.store.solace.admin.password }}"

[websubhub.config.delivery]
# timeout = {{ .Values.deployment.config.delivery.timeout }}
timeout = 60.0

[websubhub.config.delivery.retry]
count = {{ .Values.deployment.config.delivery.retry.count }}
# interval = {{ .Values.deployment.config.delivery.retry.interval }}
interval = 2.0
# backOffFactor = {{ .Values.deployment.config.delivery.retry.backOffFactor }}
backOffFactor = 2.0
# maxWaitInterval = {{ .Values.deployment.config.delivery.retry.maxWaitInterval }}
maxWaitInterval = 20.0
statusCodes = {{ .Values.deployment.config.delivery.retry.statusCodes | toJson }}

[ballerina.log]
level = "{{ .Values.logging.level }}"

[ballerina.http.traceLogAdvancedConfig]
console = true
