apiVersion: v1
name: wso2websubhub
version: 1.0.0
appVersion: "1.0.0"
description: A Helm chart for the deployment of WSO2 WebSubHub
icon: https://wso2.cachefly.net/wso2/sites/all/images/wso2logo.svg
