deployment:
  replicas: 1
  image:
    repository: wso2/wso2websubhub
    tag: latest
    pullPolicy: IfNotPresent

  config:
    server:
      port: 9000
      id: "websubhub-node"
      secureSocket:
        enable: true
        keystore:
          path: "conf/resources/wso2websubhub.jks"
          password: "wso2carbon"

    state:
      snapshot:
        url: "http://websubhub-consolidator-service:10001/snapshot"
      events:
        topic: "websub-events"
        consumerId: "hub-websub-events-consumer"

    store:
      solace:
        url: "tcp://solace-pubsubplus-dev:55554"
        vpnName: "default"
        username: "admin"
        password: "password"
        consumerReceiveTimeOut: 10.0
        admin:
          url: "http://solace-pubsubplus-dev:8080/SEMP/v2/config"
          username: "admin"
          password: "password"
          timeOut: 30.0

    delivery:
      timeout: 60.0
      retry:
        count: 3
        interval: 2.0
        backOffFactor: 2.0
        maxWaitInterval: 20.0
        statusCodes: [500, 502, 503]

logging:
  level: "INFO"

service:
  type: ClusterIP
  port: 9000

ingress:
  enabled: false
  hostname: wso2-websubhub.local
  path: /hub
  pathType: Prefix
